name: Deploy para VPS

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/Pasta_Teste
            git pull origin main
            # Caso a aplicação precise ser reiniciada, descomente a linha abaixo
            # sudo systemctl restart minha-app
            #
